# Default values for ws.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  pullPolicy: IfNotPresent

imagePullSecrets: 
  - name: acr-secret

secretsCloudProvider: vault

deployment:
  stateless: true
  automountServiceAccountToken: false

probes:
  enabled: false

service:
  enabled: false
  type: ClusterIP

configmap:
  enabled: false

ingress:
  enabled: false
  annotations:

secretProviderClass:
  enabled: false

autoscaling:
  enabled: false
  
serviceAccount:
  create: false

