{
 "title": "B2B Seller",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": "supplier-prod" },
   { "name": "namespace", "label": "Namespace", "query": "supplier-prod" },
   { "name": "container", "label": "Container", "query": "supplierbackend" }
  ]
 },
 "panels": [
  { "title": "System Live Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Apdex Score",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(rate(http_request_duration_seconds_bucket{le=\"0.25\",status=~\"^2..\", job=~\"$job\"}[4m]))\n+\nsum(rate(http_request_duration_seconds_bucket{le=\"1\",status=~\"^2..\", job=~\"$job\"}[4m])))\n/\n(2* sum(rate(http_request_duration_seconds_count{job=~\"$job\"}[4m])))"
    }
   ]
  },
  {
   "title": "Probe Error Ratio",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{status=~\"[45]..\",job=\"supplier-prod\"}[5m]) or on() vector(0)) \r\n/\r\nsum(increase(http_request_duration_seconds_count{job=\"supplier-prod\"}[5m]))",
     "legendFormat": "API Errors"
    }
   ]
  },
  {
   "title": "Login Error Ratio",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{status=~\"[45]..\", job=~\"$job\", path=\"/auth/login\"}[5m]) or on() vector(0))  / sum(increase(http_request_duration_seconds_count{job=~\"$job\",path=\"/auth/login\"}[5m]) or on() vector(1)  ) ",
     "legendFormat": "OTP Ratio 5m"
    }
   ]
  },
  {
   "title": "Requests in Processing",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(nodejs_active_requests_total{job=~\"$job\"}[5m]))",
     "legendFormat": "{{$value}}"
    }
   ]
  },
  {
   "title": "HTTP Responses by status code",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (status) (rate(http_request_duration_seconds_count{job=~\"$job\"}[4m])) * 60",
     "legendFormat": "Status: {{status}}"
    }
   ]
  },
  {
   "title": "OTP Error Ratio",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{status=~\"[45]..\", job=~\"$job\", path=\"/auth/verify-otp\"}[5m]) or on() vector(0))  / sum(increase(http_request_duration_seconds_count{job=~\"$job\",path=\"/auth/verify-otp\"}[5m]) or on() vector(1)  ) ",
     "legendFormat": "OTP Ratio 5m"
    }
   ]
  },
  {
   "title": "Running Instances",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_info{container=~\"$container\"}) by (image)",
     "legendFormat": "{{image}}"
    }
   ]
  },
  {
   "title": "CPU Utilization ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", container=~\"$container\"}[4m])) "
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg (rate(http_request_duration_seconds_sum{job=~\"$job\"}[5m]))\r\n/\r\navg (rate(http_request_duration_seconds_count{job=~\"$job\"}[5m])) "
    }
   ]
  },
  {
   "title": "Apdex Score: target 250ms, tolerated: 1000ms",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n  sum(rate(http_request_duration_seconds_bucket{le=\"0.25\",status=~\"^2..\", job=~\"$job\"}[4m]))\n+\n  sum(rate(http_request_duration_seconds_bucket{le=\"1\",status=~\"^2..\", job=~\"$job\"}[4m]))\n) / (2* sum(rate(http_request_duration_seconds_count{job=~\"$job\"}[4m])))",
     "legendFormat": "Apdex"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(container_memory_working_set_bytes{container=~\"$container\"})/max(kube_pod_container_resource_requests{container=~\"$container\"})"
    }
   ]
  },
  {
   "title": "Verify OTP",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{job=~\"$job\",path=\"/auth/verify-otp\"}[4m])*60) by(status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "Http Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{job=~\"$job\",status=~\"[45]..\"}[5m]))",
     "legendFormat": "failed requests rate"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_count{job=~\"$job\"}[5m]))",
     "legendFormat": "all requests rate"
    }
   ]
  },
  {
   "title": "Throughput by status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{job=\"supplier-prod\"}[5m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(path,method) (rate(http_request_duration_seconds_sum{job=~\"$job\"}[5m]))\n/\nsum by (path, method)(rate(http_request_duration_seconds_count{job=~\"$job\"}[5m])) ",
     "legendFormat": "{{path}} ({{method}})"
    }
   ]
  },
  {
   "title": "Top HTTP paths used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (path,method) (rate(http_request_duration_seconds_count{job=~\"$job\"}[5m]))",
     "legendFormat": "{{method}}: {{path}}"
    }
   ]
  },
  {
   "title": "Top Failed Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum  by(path,status, method)(rate(http_request_duration_seconds_count{job=~\"$job\",status=~\"^[45]..\"}[4m])*60) ",
     "legendFormat": "{{path}}:{{status}}-{{method}}"
    }
   ]
  },
  {
   "title": "Historic P90 response time by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_request_duration_seconds_bucket{job=~\"$job\"}[5m])) by (le,method))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Historic P50 response time by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(irate(http_request_duration_seconds_bucket{job=~\"$job\"}[5m])) by (le,method)) ",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Basic Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Utilization per Instance",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(container_memory_working_set_bytes{container=~\"$container\"}) by (pod) / (1024*1024)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "CPU Utilization per Pod",
     "type": "stat",
     "gridPos": { "h": 9, "w": 13, "x": 11, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by(pod)  (rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", container=~\"$container\"}[4m])) "
      }
     ]
    },
    {
     "title": "Process Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 16, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{job=~\"$job\"}",
       "legendFormat": "Process Memory - {{pod}}"
      },
      {
       "expr": "nodejs_heap_size_total_bytes{job=~\"$job\"}",
       "legendFormat": "Heap Total - {{pod}}"
      },
      {
       "expr": "nodejs_heap_size_used_bytes{job=~\"$job\"}",
       "legendFormat": "Heap Used - {{pod}}"
      },
      {
       "expr": "nodejs_external_memory_bytes{job=~\"$job\"}",
       "legendFormat": "External Memory - {{instance}}"
      }
     ]
    },
    {
     "title": "Heap Used Detail",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "nodejs_heap_space_size_used_bytes{job=~\"$job\"}",
       "legendFormat": "Heap Used - {{pod}} - {{space}}"
      }
     ]
    },
    {
     "title": "Heap Total Detail",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "nodejs_heap_space_size_total_bytes{job=~\"$job\"}",
       "legendFormat": "Heap Total - {{space}}"
      }
     ]
    },
    {
     "title": "Heap Available Detail",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "nodejs_heap_space_size_available_bytes{job=~\"$job\"}",
       "legendFormat": "Heap Used - {{space}}"
      }
     ]
    },
    {
     "title": "Event Loop Lag",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "nodejs_eventloop_lag_seconds{job=~\"$job\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Active Handlers/Requests Total",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nodejs_active_handles_total{job=~\"$job\"}",
       "legendFormat": "Active Handler"
      },
      {
       "expr": "nodejs_active_requests_total{job=~\"$job\"}",
       "legendFormat": "Active Request"
      }
     ]
    }
   ]
  }
 ]
}