{
 "title": "blackbox",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": " status_code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "probe_http_status_code" }
   ]
  },
  {
   "title": "HTTP-STATUS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "probe_http_status_code{instance=\"https://metrics.cassbana.com\", job=\"blackbox\"}"
    },
    {
     "expr": "probe_http_status_code{instance=\"https://observe-prod.cassbana.com\", job=\"blackbox\"}\n"
    }
   ]
  },
  {
   "title": "Success Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "probe_success" }
   ]
  },
  {
   "title": "HTTP Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "probe_http_duration_seconds" }
   ]
  },
  {
   "title": "PROBE-DURATION",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "probe_duration_seconds" }
   ]
  },
  {
   "title": "probe_http_ssl",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    { "expr": "probe_http_ssl" }
   ]
  },
  {
   "title": "SSL Expiry",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{} - time()"
    }
   ]
  }
 ]
}