{
 "title": "Cashkateb Upload",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": "cashkatebupload-prod" },
   { "name": "job", "query": "cashkatebupload-prod" }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilization ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", container=\"cashkateb-upload\"}[4m])) "
    }
   ]
  },
  {
   "title": "CPU Utilization per Pod",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(pod)  (rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", container=\"cashkateb-upload\"}[4m])) "
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(container_memory_working_set_bytes{container=\"cashkateb-upload\"})/max(kube_pod_container_resource_requests{container=\"cashkateb-upload\"})"
    },
    {
     "expr": "avg(avg_over_time(system_memory_utilization{app=\"cashkateb-upload\",state=\"used\"}[4m]))"
    }
   ]
  },
  {
   "title": "Memory Utilization per Instance",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(container_memory_working_set_bytes{namespace=~\"$namespace\", container=\"cashkateb-upload\"}) by (pod) / (1024*1024)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Running Instances",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_info{container=~\"cashkateb-backend|cashkateb-upload\"}) by (image)",
     "legendFormat": "{{image}}"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(path,method) (rate(http_request_duration_seconds_sum{job=~\"$job\"}[5m]))\r\n/\r\nsum by (path, method)(rate(http_request_duration_seconds_count{job=~\"$job\"}[5m])) ",
     "legendFormat": "{{path}} ({{method}})"
    }
   ]
  },
  {
   "title": "Heap Total Detail",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_space_size_total_bytes{job=~\"$job\"}",
     "legendFormat": "Heap Total - {{space}}"
    }
   ]
  },
  {
   "title": "Heap Available Detail",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_space_size_available_bytes{job=~\"$job\"}",
     "legendFormat": "Heap Used - {{space}}"
    }
   ]
  },
  {
   "title": "Heap Used Detail",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_space_size_used_bytes{job=~\"$job\"}",
     "legendFormat": "Heap Used - {{pod}} - {{space}}"
    }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"$job\"}",
     "legendFormat": "Process Memory - {{pod}}"
    },
    {
     "expr": "nodejs_heap_size_total_bytes{job=~\"$job\"}",
     "legendFormat": "Heap Total - {{pod}}"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{job=~\"$job\"}",
     "legendFormat": "Heap Used - {{pod}}"
    },
    {
     "expr": "nodejs_external_memory_bytes{job=~\"$job\"}",
     "legendFormat": "External Memory - {{instance}}"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{job=~\"$job\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  }
 ]
}