{
 "title": "Communication Service Dashboard",
 "description": "node.js prometheus client basic metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": "comm-prod-metrics.cassbana.com:80"
   }
  ]
 },
 "panels": [
  {
   "title": "SMS Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum(rate(consumed_sms_messages_counter_total{app=\"projectx-communicationservice\",status=~\"error|provider_error\"}[5m]))/sum(rate(consumed_sms_messages_counter_total{app=\"projectx-communicationservice\"}[5m]))) or vector(0)",
     "legendFormat": "Error Rate"
    }
   ]
  },
  {
   "title": "Infopip Success Sent SMS",
   "type": "stat",
   "description": "Number of success SMS sending operations using Infopip SMS provider",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Message" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "infopip_success_messages_counter{job=\"communication\"}"
    }
   ]
  },
  {
   "title": "Infopip Failed Sent SMS",
   "type": "stat",
   "description": "Number of failed SMS sending operations using Infopip SMS provider",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Message" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "infopip_failed_messages_counter{job=\"communication\"}"
    }
   ]
  },
  {
   "title": "SMS Messages",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "consumed_sms_messages_counter_total{job=\"communication\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Average time to deliver",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(sms_time_to_deliver_sum{app=\"projectx-communicationservice\"}[5m])) / avg(rate(sms_time_to_deliver_count{app=\"projectx-communicationservice\"}[5m]))",
     "legendFormat": "avg delivery time"
    }
   ]
  },
  {
   "title": "Communication Service SMS Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(consumed_sms_messages_counter_total{app=\"projectx-communicationservice\",status=\"error\"}[5m]))",
     "legendFormat": "failed requests rate"
    },
    {
     "expr": "sum(rate(consumed_sms_messages_counter_total{app=\"projectx-communicationservice\"}[5m]))",
     "legendFormat": "all requests rate"
    }
   ]
  },
  {
   "title": "Cequens Account Credit Balance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "avg(sms_provider_balance_gauge{app=\"projectx-communicationservice\",provider=\"cequens\"})"
    }
   ]
  },
  {
   "title": "Cequens Success Sent SMS",
   "type": "timeseries",
   "description": "Number of success SMS sending operations using Cequens SMS provide ",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Message" } },
   "targets": [
    {
     "expr": "avg(cequens_success_messages_counter_total{app=\"projectx-communicationservice\"})"
    }
   ]
  },
  {
   "title": "Avg Time to consume SMS Message",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(rate(sms_time_to_consume_sum{app=\"projectx-communicationservice\"}[5m])) / avg(rate(sms_time_to_consume_count{app=\"projectx-communicationservice\"}[5m]))",
     "legendFormat": "Average time to consume"
    }
   ]
  },
  {
   "title": "Up time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "avg_over_time(\r\n  (\r\n    sum without() (up{job=\"communication\"})\r\n      or\r\n    (0 * sum_over_time(up{job=\"communication\"}[7d]))\r\n  )[7d:5m] \r\n)"
    }
   ]
  },
  { "title": "CPU and Ram", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Memory Utilization per Instance",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(container_memory_working_set_bytes{container=\"projectx-communicationservice\"}) by (pod) / (1024*1024)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Utilization per Pod",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(pod)  (rate(container_cpu_usage_seconds_total{namespace=\"projectx-prod\", container=\"projectx-communicationservice\"}[4m])) "
    }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"communication\"}",
     "legendFormat": "Process Memory"
    },
    {
     "expr": "nodejs_heap_size_total_bytes{job=~\"communication\"}",
     "legendFormat": "Heap Total"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{job=~\"communication\"}",
     "legendFormat": "Heap Used"
    },
    {
     "expr": "nodejs_external_memory_bytes{job=~\"communication\"}",
     "legendFormat": "External Memory"
    }
   ]
  },
  {
   "title": "Heap Used Detail",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_space_size_used_bytes{job=~\"communication\"}",
     "legendFormat": "Heap Used - {{pod}} - {{space}}"
    }
   ]
  },
  {
   "title": "Active Handlers/Requests Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nodejs_active_handles_total{job=~\"communication\"}",
     "legendFormat": "Active Handler"
    },
    {
     "expr": "nodejs_active_requests_total{job=~\"communication\"}",
     "legendFormat": "Active Request"
    }
   ]
  },
  {
   "title": "Heap Available Detail",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_space_size_available_bytes{job=~\"communication\"}",
     "legendFormat": "Heap Used - {{space}}"
    }
   ]
  },
  {
   "title": "Heap Total Detail",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_space_size_total_bytes{job=~\"communication\"}",
     "legendFormat": "Heap Total - {{space}}"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{job=~\"communication\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Process Restart Times",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(process_start_time_seconds{instance=~\"$instance\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node.js Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(nodejs_version_info{instance=~\"$instance\"}) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  }
 ]
}