{
 "title": "kafka-topic",
 "tags": [ "kafka" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(kafka_server_replicamanager_partitioncount, cluster)"
    }
   },
   {
    "name": "topic",
    "label": "topic",
    "query": {
     "query": "label_values(kafka_server_brokertopicmetrics_messagesin_total{cluster=~\"$cluster\"}, topic)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "replicas",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kafka_log_log_size{topic=~\"dataCollectionProd\"}) / count(sum(kafka_log_log_size{topic=~\"dataCollectionProd\"}) by (partition))"
    }
   ]
  },
  {
   "title": "partitions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(sum(kafka_log_log_size{topic=\"dataCollectionProd\"}) by (partition))"
    }
   ]
  },
  {
   "title": "partitions by broker",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count(kafka_log_log_size{service=\"broker-kafka-jmx-metrics\",topic=\"dataCollectionProd\"}))",
     "legendFormat": "total"
    },
    {
     "expr": "count(kafka_log_log_size{service=\"broker-kafka-jmx-metrics\",topic=\"__consumer_offsets\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "data size by broker",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_log_log_size{cluster=~\"$cluster\",topic=\"dataCollectionProd\"})",
     "legendFormat": "total"
    },
    {
     "expr": "sum(kafka_log_log_size{cluster=~\"$cluster\",topic=\"dataCollectionStg\"}) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(kafka_log_log_size{cluster=~\"$cluster\",topic=\"__consumer_offsets\"}) by (instance)"
    }
   ]
  },
  {
   "title": "bytes in by broker",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kafka_server_brokertopicmetrics_bytesinpersec_count{cluster=~\"$cluster\",topic=\"__consumer_offsets\"}[10m])) / 10 / 60",
     "legendFormat": "total"
    },
    {
     "expr": "sum(delta(kafka_server_brokertopicmetrics_bytesinpersec_count{cluster=~\"$cluster\",topic=\"dataCollectionProd\"}[10m])) by (instance) / 10 / 60",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "message in /s by broker",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kafka_server_brokertopicmetrics_messagesinpersec_count{topic=\"__consumer_offsets\"}[10m])) / 10 / 60",
     "legendFormat": "total"
    },
    {
     "expr": "sum(delta(kafka_server_brokertopicmetrics_messagesinpersec_count{topic=\"__consumer_offsets\"}[10m])) by (instance) / 10 / 60",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "log start offset",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_log_log_logstartoffset{cluster=~\"$cluster\",topic=\"dataCollectionProd\"}) by (partition) / (count(kafka_log_log_logstartoffset{cluster=~\"$cluster\",topic=\"dataCollectionProd\"}) by (partition))",
     "legendFormat": "partition {{partition}}"
    }
   ]
  },
  {
   "title": "data size by partition",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_log_log_size{cluster=~\"$cluster\",topic=\"dataCollectionProd\"}) by (partition)",
     "legendFormat": "{{partition}}"
    }
   ]
  },
  {
   "title": "consume rate /s",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kafka_server_delayedfetchmetrics_total_expirespersec_fetchertype_consumer_count{cluster=~\"$cluster\",topic=~\"$topic\"}[10m])) by (consumergroup) / 10 / 60",
     "legendFormat": "{{consumergroup}}"
    }
   ]
  },
  {
   "title": "bytes out by broker",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kafka_server_brokertopicmetrics_total_bytesoutpersec_count{cluster=~\"$cluster\",topic=~\"$topic\"}[10m])) / 10 / 60",
     "legendFormat": "total"
    },
    {
     "expr": "sum(delta(kafka_server_brokertopicmetrics_total_bytesoutpersec_count{cluster=~\"$cluster\",topic=~\"$topic\"}[10m])) by (instance) / 10 / 60",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "under replicated by broker",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_under_replicated_partition{cluster=~\"$cluster\",topic=~\"$topic\"} > 0) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "log end offset",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_log_log_logendoffset{cluster=~\"$cluster\",topic=~\"$topic\"}) by (partition) / (count(kafka_log_log_logendoffset{cluster=~\"$cluster\",topic=~\"$topic\"}) by (partition))",
     "legendFormat": "partition {{partition}}"
    }
   ]
  },
  {
   "title": "consume lag",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 1, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{cluster=~\"$cluster\",topic=~\"$topic\"}) by (consumergroup)",
     "legendFormat": "{{consumergroup}}"
    }
   ]
  }
 ]
}