{
 "title": "Keycloak Metrics",
 "description": "Monitoring keycloak metrics",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(keycloak_logins,instance)"
    }
   },
   {
    "name": "realm",
    "label": "Realm",
    "query": {
     "query": "label_values(keycloak_logins{instance=\"$instance\",job=\"keycloak\",provider=\"keycloak\"},realm)"
    }
   },
   {
    "name": "ClientId",
    "label": "ClientId",
    "query": {
     "query": "label_values(keycloak_logins{instance=\"$instance\",job=\"keycloak\",provider=\"keycloak\",realm=\"$realm\"},client_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "4xx and 5xx Responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(keycloak_response_errors[3m])",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_max{instance=\"identity.cassbana.com:80\",job=\"keycloak\"})",
     "legendFormat": "Max"
    },
    {
     "expr": "sum(jvm_memory_bytes_committed{instance=\"identity.cassbana.com:80\",job=\"keycloak\"})",
     "legendFormat": "Comitted"
    },
    {
     "expr": "sum(jvm_memory_bytes_used{instance=\"identity.cassbana.com:80\",job=\"keycloak\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Logins Per CLIENT",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(keycloak_logins{instance=\"identity.cassbana.com:80\"}) by (client_id)",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Percentage Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(jvm_memory_bytes_used{instance=\"identity.cassbana.com:80\",job=\"keycloak\"} /jvm_memory_bytes_committed{instance=\"identity.cassbana.com:80\",job=\"keycloak\"}) * 100",
     "legendFormat": "Used / Committed"
    }
   ]
  },
  {
   "title": "Login Errors on realm $realm",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(keycloak_failed_login_attempts{instance=\"identity.cassbana.com:80\",job=\"keycloak\",provider=\"keycloak\",realm=\"cassbana\"})",
     "legendFormat": "{{error}}"
    }
   ]
  },
  {
   "title": "Current Memory HEAP",
   "type": "gauge",
   "description": "Memory currently being used by Keycloak.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{instance=\"identity.cassbana.com:80\", area=\"heap\"})*100/sum(jvm_memory_bytes_max{instance=\"identity.cassbana.com:80\", area=\"heap\"})\n"
    }
   ]
  },
  {
   "title": "Current Memory nonHEAP",
   "type": "gauge",
   "description": "Memory currently being used by Keycloak.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{instance=\"identity.cassbana.com:80\", area=\"nonheap\"})*100/sum(jvm_memory_bytes_max{instance=\"identity.cassbana.com:80\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "Logins Per REALM",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(keycloak_logins{instance=\"identity.cassbana.com:80\"}) by (realm)",
     "legendFormat": "{{realm}}"
    }
   ]
  },
  {
   "title": "Login Errors for $ClientId",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(keycloak_failed_login_attempts{instance=\"identity.cassbana.com:80\",job=\"keycloak\",provider=\"keycloak\",realm=\"cassbana\"})"
    }
   ]
  },
  {
   "title": "Logins per REALM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (realm)(increase(keycloak_logins{instance=\"identity.cassbana.com:80\",job=\"keycloak\"}[1h]))",
     "legendFormat": "{{realm}}"
    }
   ]
  },
  {
   "title": "Logins per CLIENT on realm $realm",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(keycloak_logins{instance=\"identity.cassbana.com:80\",job=\"keycloak\",realm=\"cassbana\",provider=\"keycloak\"})",
     "legendFormat": "{{client_id}}"
    }
   ]
  }
 ]
}