{
 "title": "MongoDB Health",
 "description": "MongoDB basic dashboard for health & monitoring",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": "mongocashkateb,mongocommsvc,mongodbdata"
   }
  ]
 },
 "panels": [
  {
   "title": "Mongodb Total Asserts",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_asserts_total{namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Query Planner Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg (rate(mongodb_mongod_metrics_query_executor_total{state=\"scanned_objects\"}[5m]) or \nirate(mongodb_mongod_metrics_query_executor_total{state=\"scanned_objects\"}[5m]))",
     "legendFormat": "Scanned Objects / sec"
    }
   ]
  },
  { "title": "Pods & Diagnostics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "MongoDB Instance Uptime",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_instance_uptime_seconds{namespace=\"$namespace\"}",
     "legendFormat": "Uptime Second"
    }
   ]
  },
  {
   "title": "Replication Lag",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "mongodb_mongod_replset_member_replication_lag"
    }
   ]
  },
  {
   "title": "Op Execution Time (Latency)",
   "type": "timeseries",
   "description": "Average latency of operations (classified by read or write command)",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg (rate(mongodb_mongod_op_latencies_latency_total{type=~\"read\"}[5m]) / (rate(mongodb_mongod_op_latencies_ops_total{type=~\"read\"}[5m]) > 0) or irate(mongodb_mongod_op_latencies_latency_total{type=~\"read\"}[5m]) / (irate(mongodb_mongod_op_latencies_ops_total{type=~\"read\"}[5m]) > 0))",
     "legendFormat": "Read"
    },
    {
     "expr": "avg (rate(mongodb_mongod_op_latencies_latency_total{type=~\"write\"}[5m]) / (rate(mongodb_mongod_op_latencies_ops_total{type=~\"write\"}[5m]) > 0) or irate(mongodb_mongod_op_latencies_latency_total{type=~\"write\"}[5m]) / (irate(mongodb_mongod_op_latencies_ops_total{type=~\"write\"}[5m]) > 0))",
     "legendFormat": "Write"
    },
    {
     "expr": "avg (rate(mongodb_mongod_op_latencies_latency_total{type=\"command\"}[5m]) / (rate(mongodb_mongod_op_latencies_ops_total{type=\"command\"}[5m]) > 0) or irate(mongodb_mongod_op_latencies_latency_total{type=\"command\"}[5m]) / (irate(mongodb_mongod_op_latencies_ops_total{type=\"command\"}[5m]) > 0))",
     "legendFormat": "Command"
    }
   ]
  },
  {
   "title": "OpCounters",
   "type": "timeseries",
   "description": "Ops/sec, classified by legacy wire protocol type (query, insert, update, delete, getmore).",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum (rate(mongodb_op_counters_total{type!=\"command\"}[5m]) or \r\nirate(mongodb_op_counters_total{type!=\"command\"}[5m]))",
     "legendFormat": "MongoDB OpCounters Total"
    }
   ]
  },
  { "title": "MongoDB Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Replica Set: Network Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "Recv"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "Send"
    }
   ]
  },
  {
   "title": "MongoDB Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (service_name) (max_over_time(mongodb_mongod_connections{state=\"current\"}[5m]) or \nmax_over_time(mongodb_mongos_connections{state=\"current\"}[5m]) or\nmax_over_time(mongodb_connections{state=\"current\"}[5m]))",
     "legendFormat": "Current"
    },
    {
     "expr": "avg by (service_name) (max_over_time(mongodb_mongod_connections{state=\"active\"}[5m]) or \nmax_over_time(mongodb_mongos_connections{state=\"active\"}[5m]) or\nmax_over_time(mongodb_connections{state=\"active\"}[5m]))",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "MongoDB Exporter: Network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "Recv"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "Send"
    }
   ]
  },
  { "title": "Data Volumes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Data: % Volume Available",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\nsum without(instance, node) (kubelet_volume_stats_available_bytes{namespace=\"$namespace\"})\n/\n\nsum without(instance, node) (kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\"})\n) * 100"
    }
   ]
  },
  {
   "title": "Persistent Volumes: Data",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "(\r\n  sum without(instance, node) (kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\"})\r\n  -\r\n  sum without(instance, node) (kubelet_volume_stats_available_bytes{namespace=\"$namespace\"})\r\n)",
     "legendFormat": "Data: Used Space"
    },
    {
     "expr": "sum without(instance, node) (kubelet_volume_stats_available_bytes{namespace=\"$namespace\"})",
     "legendFormat": "Data: Free Space"
    }
   ]
  },
  {
   "title": "Persistent Volumes: Logs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "(\r\n  sum without(instance, node) (kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\"})\r\n  -\r\n  sum without(instance, node) (kubelet_volume_stats_available_bytes{namespace=\"$namespace\"})\r\n)",
     "legendFormat": "Logs: Used Space"
    },
    {
     "expr": "(kubelet_volume_stats_available_bytes{namespace=\"$namespace\")",
     "legendFormat": "Logs: Free Space"
    }
   ]
  },
  {
   "title": "Logs: % Volume Available",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\nsum without(instance, node) (kubelet_volume_stats_available_bytes{namespace=\"$namespace\"})\n/\n\nsum without(instance, node) (kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\"})\n) * 100"
    }
   ]
  },
  {
   "title": "Total Volume Capacity: Logs",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without(instance, node) (kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\"})",
     "legendFormat": "Logs"
    }
   ]
  },
  {
   "title": "Total Volume Capacity: Data",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 8, "x": 14, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without(instance, node) (kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\"})",
     "legendFormat": "Data"
    }
   ]
  },
  { "title": "Apps Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Memory : apps-server",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 1, "y": 48 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Network : Apps Server",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 48 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "Recv"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "Send"
    }
   ]
  }
 ]
}