{
 "title": "ocr prod flask",
 "description": "Flask",
 "tags": [ "flask" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Total Requests Per Hour",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "flask_http_request_total{job='ocr-prod', method='POST'}"
    }
   ]
  },
  {
   "title": "Requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{path=\"/ocr\",method=\"POST\"}[4m]) *60) by (path, status)",
     "legendFormat": "{{path}} {{ status }}"
    }
   ]
  },
  {
   "title": "Errors per minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{status!=\"200\"}[5m]) * 60)",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(flask_http_request_duration_seconds_count{}[5m])) by (path,method)",
     "legendFormat": "{{ path }} - {{method}}"
    }
   ]
  },
  {
   "title": "Request duration [s] - 0.5",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(flask_http_request_duration_seconds_bucket{status=\"200\"}[10m]))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Average response time [30s]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_sum{status=\"200\"}[4m])\n/\nrate(flask_http_request_duration_seconds_count{status=\"200\"}[4m])) by (path, method)",
     "legendFormat": "{{ path }} - {{method}}"
    }
   ]
  },
  {
   "title": "Requests under 250ms",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "increase(flask_http_request_duration_seconds_bucket{status=\"200\",le=\"0.25\"}[5m]) \n/ ignoring (le) increase(flask_http_request_duration_seconds_count{status=\"200\"}[5m])",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Request duration [s] - 0.9",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 10, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(flask_http_request_duration_seconds_bucket{status=\"200\"}[5m]))",
     "legendFormat": "{{ path }}"
    }
   ]
  }
 ]
}