{
 "title": "payment-latest-dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "R2P error ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{status=~\"[45]..\", job=\"paymentservice-prod\", path=\"/api/v1/transaction/request-to-pay\"}[5m]) or on() vector(0))  / sum(increase(http_request_duration_seconds_count{job=\"paymentservice-prod\",path=\"/api/v1/transaction/request-to-pay\"}[5m]) or on() vector(1)  ) "
    }
   ]
  },
  {
   "title": " Probe Error Ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{status=~\"[45]..\",job=\"paymentservice-prod\"}[5m]) or on() vector(0)) / sum(increase(http_request_duration_seconds_count{job=\"paymentservice-prod\"}[5m]))",
     "legendFormat": "API Errors"
    }
   ]
  },
  {
   "title": "Apdex Score",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "(\n  sum(rate(http_request_duration_seconds_bucket{le=\"0.25\",status=~\"^2..\", job=\"paymentservice-prod\"}[5m]))\n+\n  sum(rate(http_request_duration_seconds_bucket{le=\"1\",status=~\"^2..\", job=\"paymentservice-prod\"}[5m]))\n) / (2* sum(rate(http_request_duration_seconds_count{job=\"paymentservice-prod\"}[5m])))"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "avg (rate(http_request_duration_seconds_sum{job=\"paymentservice-prod\"}[5m]))\n/\navg (rate(http_request_duration_seconds_count{job=\"paymentservice-prod\"}[5m])) "
    }
   ]
  },
  {
   "title": "Requests in Processing",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 19, "y": 0 },
   "targets": [
    {
     "expr": "sum(sum_over_time(nodejs_active_requests_total{job=\"paymentservice-prod\"}[5m]))"
    }
   ]
  },
  {
   "title": "HTTP Responses by status code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by (status) (rate(http_request_duration_seconds_count{job=\"paymentservice-prod\"}[4m])) * 60"
    },
    {
     "expr": "sum by (status) (rate(http_request_duration_seconds_count{job=\"paymentservice-prod\",status=\"409\"}[4m]))*60"
    }
   ]
  },
  {
   "title": "CPU Utilization ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 11, "y": 7 },
   "targets": [
    {
     "expr": "avg (rate(container_cpu_usage_seconds_total{job=\"paymentservice-prod\"}[4m])) ",
     "legendFormat": "usage"
    },
    {
     "expr": "avg(avg_over_time (system_cpu_utilization{job=\"paymentservice-prod\" ,state=~\"system|user\"}[4m]))",
     "legendFormat": "utilization"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(container_memory_working_set_bytes{container=\"paymentservice\"})/max(kube_pod_container_resource_requests{container=\"paymentservice\"})"
    }
   ]
  },
  {
   "title": "Running Instances",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_info{container=\"paymentservice\"}) by (image)"
    }
   ]
  },
  {
   "title": "Apdex Score: target 250ms, tolerated: 1000ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "(\n  sum(rate(http_request_duration_seconds_bucket{le=\"0.25\",status=~\"^2..\",job=\"paymentservice-prod\"}[5m]))\n+\n  sum(rate(http_request_duration_seconds_bucket{le=\"1\",status=~\"^2..\", job=\"paymentservice-prod\"}[5m]))\n) / (2* sum(rate(http_request_duration_seconds_count{job=\"paymentservice-prod\"}[5m])))",
     "legendFormat": "Apdex"
    }
   ]
  },
  {
   "title": "R2P",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count{job=\"paymentservice-prod\",path=\"/api/v1/transaction/request-to-pay\"}*60) by(status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{job=\"paymentservice-prod\",status=~\"[45]..\"}[5m]))"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_count{job=\"paymentservice-prod\"}[5m]))"
    }
   ]
  },
  {
   "title": "average response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "sum by(path,method) (rate(http_request_duration_seconds_sum{job=\"paymentservice-prod\"}[5m]))\n/\nsum by (path, method)(rate(http_request_duration_seconds_count{job=\"paymentservice-prod\"}[5m])) ",
     "legendFormat": "{{path}} ({{method}})"
    }
   ]
  },
  {
   "title": "Active Handlers/Requests Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nodejs_active_handles_total{job=\"paymentservice-prod\"}",
     "legendFormat": "Active Handler - {{instance}}"
    },
    {
     "expr": "nodejs_active_requests_total{job=\"paymentservice-prod\"}",
     "legendFormat": "Active Request - {{instance}}"
    }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"paymentservice-prod\"}",
     "legendFormat": "Process Memory - {{instance}}"
    },
    {
     "expr": "nodejs_heap_size_total_bytes{job=\"paymentservice-prod\"}",
     "legendFormat": "Heap Total - {{instance}}"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{instance=~\"$instance\"}",
     "legendFormat": "Heap Used - {{instance}}"
    },
    {
     "expr": "nodejs_external_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "External Memory - {{instance}}"
    }
   ]
  },
  {
   "title": "Throughput by status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{job=\"paymentservice-prod\"}[5m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Top HTTP paths used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (path,method) (rate(http_request_duration_seconds_count{job=\"paymentservice-prod\"}[5m]))",
     "legendFormat": "{{method}}: {{path}}"
    }
   ]
  },
  {
   "title": " Top Failed Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "sum  by(path,status, method)(rate(http_request_duration_seconds_count{job=\"paymentservice-prod\",status=~\"^[45]..\"}[5m])*60) ",
     "legendFormat": "{{path}}:{{status}}-{{method}}"
    }
   ]
  },
  {
   "title": "Historic P90 response time by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_request_duration_seconds_bucket{job=\"paymentservice-prod\"}[5m])) by (le,method))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Historic P45 response time by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(irate(http_request_duration_seconds_bucket{job=\"paymentservice-prod\"}[5m])) by (le,method)) ",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Heap Available Detail",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_available_bytes{job=\"paymentservice-prod\"}",
     "legendFormat": "Heap Used - {{instance}} - {{space}}"
    }
   ]
  },
  {
   "title": "Heap Used Detail",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 61 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_used_bytes{job=\"paymentservice-prod\"}",
     "legendFormat": "Heap Used - {{instance}} - {{space}}"
    }
   ]
  },
  {
   "title": "Heap Total Detail",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 61 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_total_bytes{job=\"paymentservice-prod\"}",
     "legendFormat": "Heap Total - {{instance}} - {{space}}"
    }
   ]
  }
 ]
}