{
 "title": "postgresql_keycloak",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Pg_Exporter_Status",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pg_up" }
   ]
  },
  {
   "title": "database_deadlocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_deadlocks{datname!~\"template.*|postgres\"}[5m])\n"
    }
   ]
  },
  {
   "title": "commitRate_Low",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "pg_stat_database_xact_commit" }
   ]
  },
  {
   "title": "Pg_stat_activity_count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(datname) (pg_stat_activity_count{datname!~\"template.*|postgres\"}) \n"
    }
   ]
  },
  {
   "title": "High_rollback_rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_rollback{datname!~\"template.*\"}[3m]) / rate(pg_stat_database_xact_commit{datname!~\"template.*\"}[3m])\n"
    }
   ]
  },
  {
   "title": "Toomany_Locks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "((sum(pg_locks_count)) / (pg_settings_max_locks_per_transaction * pg_settings_max_connections))  "
    }
   ]
  },
  {
   "title": "Toomany_Dead_Tuples",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "((pg_stat_user_tables_n_dead_tup > 10000) / (pg_stat_user_tables_n_live_tup + pg_stat_user_tables_n_dead_tup)) >= 0.1 unless on(instance)(pg_replication_is_replica == 1)"
    }
   ]
  }
 ]
}