{{- if .Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
    {{- include "andela.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- with .Values.configmap.configuration }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}

