{{- if .Values.deployment.stateless }}
{{- $releaseName := include "andela.releasename" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  annotations:
    # Note that this will apply to all deployments based upon this template
    secret.reloader.stakater.com/reload: {{ $releaseName }}-secret
  labels:
    {{- include "andela.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
#  {{- if not .Values.autoscaling.enabled }}
#  replicas: {{ .Values.replicaCount }}
#  {{- end }}
  selector:
    matchLabels:
      {{- include "andela.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.deployment.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "andela.selectorLabels" . | nindent 8 }}
        {{- with .Values.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      imagePullSecrets: {{ toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- if .Values.deployment.securityContext }}
      securityContext:
        {{- toYaml .Values.deployment.securityContext | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: {{ .Values.deployment.automountServiceAccountToken}}
       {{- if .Values.initContainers }}
       {{- with .Values.initContainers }}
      initContainers:
             {{- toYaml . | nindent 8 }}
       {{- end }}
       {{- end }}
      containers:
       {{- if .Values.extraContainers }}      
       {{- with .Values.extraContainers.containers }}
             {{- toYaml . | nindent 8 }}
       {{- end }}
       {{- end }}
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.deployment.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-configmap
          env:
            {{- range .Values.service.env }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef: 
                  name: {{ $releaseName }}-secret
                  key: {{ .value }}
            {{- end }}
          {{- if .Values.deployment.containerPort }}
          ports:
            - name: http
              containerPort: {{ .Values.deployment.containerPort }}
              protocol: TCP
          {{- end }}
          {{- if .Values.probes.enabled }}
          livenessProbe:
            {{- toYaml .Values.probes.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.deployment.serviceAccountName }}
      serviceAccountName: {{ .Values.deployment.serviceAccountName }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}

