{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    {{- include "andela.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}
      protocol: TCP
      name: http
{{- if .Values.service.secondPortEnabled }}
    - port: {{ .Values.service.secondPort.port }}
      targetPort: {{ .Values.service.secondPort.targetport }}
      protocol: TCP
      name: {{ .Values.service.secondPort.name }}
{{- end }}
  selector:
    {{- include "andela.selectorLabels" . | nindent 4 }}
{{- end }}

