{
 "title": "B2B",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Suppliers Number",
   "type": "stat",
   "description": "number of non-blocked suppliers",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_suppliers_registered_total{group=\"suppliers\",instance=\"qa-api.cassbana.com:443\",job=\"b2b-qa\"}"
    }
   ]
  },
  {
   "title": "Agents Number",
   "type": "stat",
   "description": "number of non-blocked agents",
   "gridPos": { "h": 8, "w": 13, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_agents_registered_total{group=\"agents\",instance=\"qa-api.cassbana.com:443\",job=\"b2b-qa\"}"
    }
   ]
  },
  {
   "title": "Merchants Number",
   "type": "stat",
   "description": "number of non-blocked merchants",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_merchants_registered_total{group=\"merchants\", instance=\"qa-api.cassbana.com:443\", job=\"b2b-qa\"}"
    }
   ]
  },
  {
   "title": "CPU Utilization ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 13, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (rate(container_cpu_usage_seconds_total{namespace=\"b2bqa\", container=\"b2b\"}[4m])) "
    }
   ]
  },
  {
   "title": "Memory Utilization per Instance",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(container_memory_working_set_bytes{namespace=~\"b2bqa\", container=\"b2b\"}) by (pod) / (1024*1024)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Container CPU Usgae",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "max(rate(container_cpu_usage_seconds_total{container=\"b2b\"}[5m])) by (container)"
    }
   ]
  },
  {
   "title": "CPU Utilization per Pod",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(pod)(rate(container_cpu_usage_seconds_total{namespace=~\"b2bqa\", container=\"b2b\"}[4m])) "
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "stat",
   "gridPos": { "h": 8, "w": 18, "x": 5, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(container_memory_working_set_bytes{container=\"b2b\"})/max(kube_pod_container_resource_requests{container=\"b2b\"})"
    }
   ]
  },
  { "title": "System Live Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } }
 ]
}