{
 "title": "CashKateb-Dashboard-test",
 "tags": [
  "cashkateb",
  "backend"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": "projectxbackend" },
   { "name": "namespace", "query": "projectx-dev" }
  ]
 },
 "panels": [
  { "title": "System Live Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Apdex Score",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(\n  sum(rate(http_request_duration_seconds_bucket{le=\"0.25\",status=~\"^2..|409|404|403|401\", app=\"cashkateb-backendservice\"}[4m]))\n+\n  sum(rate(http_request_duration_seconds_bucket{le=\"1\",status=~\"^2..|409|404|403|401\", app=\"cashkateb-backendservice\"}[4m]))\n) / (2* sum(rate(http_request_duration_seconds_count{app=\"cashkateb-backendservice\"}[4m])))"
    }
   ]
  },
  {
   "title": "Apdex Score: target 250ms, tolerated: 1000ms",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n  sum(rate(http_request_duration_seconds_bucket{le=\"0.25\",status=~\"^2..|409|404|403|401\", app=\"cashkateb-backendservice\"}[4m]))\n+\n  sum(rate(http_request_duration_seconds_bucket{le=\"1\",status=~\"^2..|409|404|403|401\", app=\"cashkateb-backendservice\"}[4m]))\n) / (2* sum(rate(http_request_duration_seconds_count{app=\"cashkateb-backendservice\"}[4m])))",
     "legendFormat": "Apdex"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg (rate(http_request_duration_seconds_sum{app=\"cashkateb-backendservice\"}[5m]))\r\n/\r\navg (rate(http_request_duration_seconds_count{app=\"cashkateb-backendservice\"}[5m])) "
    }
   ]
  },
  {
   "title": "Requests in Processing",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(nodejs_active_requests_total{app=\"cashkateb-backendservice\"}[5m]))",
     "legendFormat": "{{$value}}"
    }
   ]
  },
  {
   "title": "Running Instances",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_info{container=~\"cashkateb-backendservice|cashkateb-backendservice|cashkateb-communicationservice\"}) by (image)",
     "legendFormat": "{{image}}"
    }
   ]
  },
  {
   "title": "HTTP Responses by status code",
   "type": "stat",
   "gridPos": { "h": 6, "w": 11, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (status) (rate(http_request_duration_seconds_count{app=\"cashkateb-backendservice\"}[4m])) * 60",
     "legendFormat": "Status: {{status}}"
    }
   ]
  },
  {
   "title": "CPU Utilization ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (rate(container_cpu_usage_seconds_total{namespace=\"$job\", container=\"cashkateb-backendservice\"}[4m])) "
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(container_memory_working_set_bytes{container=\"cashkateb-backendservice\"})/max(kube_pod_container_resource_requests{container=\"cashkateb-backendservice\"})"
    }
   ]
  },
  { "title": "Http Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{app=\"cashkateb-backendservice\",status=~\"[45]..\"}[5m]))",
     "legendFormat": "failed requests rate"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_count{app=\"cashkateb-backendservice\"}[5m]))",
     "legendFormat": "all requests rate"
    }
   ]
  },
  {
   "title": "Throughput by status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{app=\"cashkateb-backendservice\"}[5m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "sum by(path,method) (rate(http_request_duration_seconds_sum{app=\"cashkateb-backendservice\"}[5m]))\n/\nsum by (path, method)(rate(http_request_duration_seconds_count{app=\"cashkateb-backendservice\"}[5m])) ",
     "legendFormat": "{{path}} ({{method}})"
    }
   ]
  },
  {
   "title": "Top HTTP paths used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (path,method) (rate(http_request_duration_seconds_count{app=\"cashkateb-backendservice\"}[5m]))",
     "legendFormat": "{{method}}: {{path}}"
    }
   ]
  },
  {
   "title": "Historic P90 response time by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_request_duration_seconds_bucket{app=\"cashkateb-backendservice\"}[5m])) by (le,method))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Historic P50 response time by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(irate(http_request_duration_seconds_bucket{app=\"cashkateb-backendservice\"}[5m])) by (le,method)) ",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Probe Error Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{status=~\"[45]..\", app=\"cashkateb-backendservice\"}[5m])) / sum(increase(http_request_duration_seconds_count{app=\"cashkateb-backendservice\"}[5m]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Verify OTP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{app=\"cashkateb-backendservice\",path=\"/api/v1/auth/verify\"}[4m])*60) by(status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Top Failed Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(path,status)(rate(http_request_duration_seconds_count{app=\"cashkateb-backendservice\",status=~\"^[45]..\"}[4m])*60) ",
     "legendFormat": "{{path}}:{{status}}"
    }
   ]
  },
  { "title": "Basic Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Memory Utilization per Instance",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(container_memory_working_set_bytes{namespace=~\"$namespace\", container=\"cashkateb-backendservice\"}) by (pod) / (1024*1024)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Utilization per Pod",
   "type": "stat",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(pod)  (rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", container=\"cashkateb-backendservice\"}[4m])) "
    }
   ]
  },
  {
   "title": "Heap Total Detail",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_space_size_total_bytes{job=~\"$job\"}",
     "legendFormat": "Heap Total - {{space}}"
    }
   ]
  },
  {
   "title": "Heap Available Detail",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_space_size_available_bytes{job=~\"$job\"}",
     "legendFormat": "Heap Used - {{space}}"
    }
   ]
  },
  {
   "title": "Heap Used Detail",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_space_size_used_bytes{job=~\"$job\"}",
     "legendFormat": "Heap Used - {{pod}} - {{space}}"
    }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"$job\"}",
     "legendFormat": "Process Memory - {{pod}}"
    },
    {
     "expr": "nodejs_heap_size_total_bytes{job=~\"$job\"}",
     "legendFormat": "Heap Total - {{pod}}"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{job=~\"$job\"}",
     "legendFormat": "Heap Used - {{pod}}"
    },
    {
     "expr": "nodejs_external_memory_bytes{job=~\"$job\"}",
     "legendFormat": "External Memory - {{instance}}"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{job=~\"$job\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Active Handlers/Requests Total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nodejs_active_handles_total{job=~\"$job\"}",
     "legendFormat": "Active Handler"
    },
    {
     "expr": "nodejs_active_requests_total{job=~\"$job\"}",
     "legendFormat": "Active Request"
    }
   ]
  },
  { "title": "Dependencies ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(mongodb_connections{namespace=\"mongocashkateb\"}[4m]))",
     "legendFormat": "Connections"
    }
   ]
  }
 ]
}