image:
  repository: sacoefrancis/balckswan
  tag: 800f9443338241d04687c34d5ee2e386c00184bc
spec:
  replicas: 1
resources:
  requests:
    memory: 100Mi
    cpu: 0.1
  limits:
    memory: 200Mi
    cpu: 0.2
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80    
configmap:
  enabled: true
  configuration:
    databaseUrl: jdbc:mysql://trojandevdb1.cerph5j4goq3.ap-south-1.rds.amazonaws.com:3306/test_db
    databaseUserName: devdb
    databasePassword: Trojan123!

service:
  enabled: true
  port: 8080
  targetport: 8080
deployment: {}

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
#    cert-manager.io/cluster-issuer: letsencrypt-dev
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
#  tls:
#    - hosts:
#        - test.dotsolved.com
#      secretName: service-tls
  hosts:
    - host: test.dotsolved.com
      paths:
        - path:  /
          pathType: Prefix
          backend:
            service:
               name: test-app-service 
               port:
                 number: 8080

